import Link from "next/link";
import StatusBadge from "@/components/admin/StatusBadge";

export default function CrudList({ title, eyebrow, createHref, editBase, search, rows, columns, deleteAction, showCreate = true }: { title: string; eyebrow: string; createHref: string; editBase: string; search?: string; rows: Record<string, unknown>[]; columns: Array<{ key: string; label: string }>; deleteAction?: (id: string) => Promise<void>; showCreate?: boolean }) {
  return <div className="p-8 text-white">
    <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-[#b3241b]">{eyebrow}</p><h1 className="mt-2 text-3xl font-black uppercase">{title}</h1></div>{showCreate && <Link href={createHref} className="bg-[#b3241b] px-5 py-3 text-[10px] font-black uppercase tracking-[0.2em]">New +</Link>}</div>
    <form className="mb-6 flex max-w-xl gap-3"><input name="q" defaultValue={search} placeholder={`Search ${title.toLowerCase()}`} className="w-full border border-white/10 bg-[#111] px-3 py-2.5 text-sm text-white outline-none focus:border-[#b3241b]" /><button className="border border-white/20 px-4 text-[10px] font-black uppercase tracking-[0.15em]">Search</button></form>
    <div className="overflow-x-auto border border-white/10 bg-[#111]"><table className="w-full text-left text-sm"><thead><tr className="border-b border-white/10 text-[10px] uppercase tracking-[0.15em] text-white/40">{columns.map((column) => <th key={column.key} className="px-4 py-3">{column.label}</th>)}<th className="px-4 py-3">Actions</th></tr></thead><tbody>{rows.map((row) => { const id = String(row._id); return <tr key={id} className="border-b border-white/5"><td className="px-4 py-3 font-bold text-white"><Link href={`${editBase}/${id}`} className="hover:text-[#f2c14e]">{String(row[columns[0].key] ?? "")}</Link></td>{columns.slice(1).map((column) => <td key={column.key} className="px-4 py-3 text-white/60">{column.key === "status" ? <StatusBadge status={String(row[column.key] ?? "")} /> : String(row[column.key] ?? "-")}</td>)}<td className="px-4 py-3"><div className="flex gap-3 text-[10px] font-bold uppercase tracking-[0.1em]"><Link href={`${editBase}/${id}`} className="text-[#f2c14e]">View</Link>{deleteAction && <form action={deleteAction.bind(null, id)}><button className="text-[#b3241b]">Delete</button></form>}</div></td></tr>; })}</tbody></table>{rows.length === 0 && <p className="p-10 text-center text-sm text-white/30">No {title.toLowerCase()} found.</p>}</div>
  </div>;
}
